### ISSUE TITLE
DeepBind on larger genes

### ISSUE THREAD

**Issue by elenichri** [teja-rostan/deepbind#1]
Hi all,

Thanks for this great tool! I have a question on its use though.
Could the user examine the binding specificity of the motifs in your models by querying a sequence > 900b introducing an upper bound change to the script? Will the algorithm work properly in this case?

In general, I was wondering if you have applied DeepBind on a genome-wide scale

Thank you very much,
Eleni

**Comment by teja-rostan** [comment]
Hi Eleni,

sorry for the late response. The upper bound can get higher, but there is still an upper bound that is regulated by the Deepbind program: http://tools.genes.toronto.edu/deepbind, for which I do not remember correctly how high the upper bound is, but is not much higher and you get a warning if you surpass it. I have applied Deepbind only on the most left sub-sequences of the promoter sequences.

Regards,
Teja
